version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.7.4
    - 2.8.0
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.3.1
    - 6.3.2
    - 6.3.3
  - dependency-name: connect-redis
    versions:
    - 5.1.0
  - dependency-name: pg-promise
    versions:
    - 10.10.1
- package-ecosystem: pip
  directory: "/ansible"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cryptography
    versions:
    - "3.2"
- package-ecosystem: cargo
  directory: "/journald-cloudwatch"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.93
- package-ecosystem: npm
  directory: "/errors-to-discord"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.893.0
- package-ecosystem: npm
  directory: "/alarms-to-discord"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.893.0
