version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/errors-to-discord"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/alarms-to-discord"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/ansible"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/journald-cloudwatch"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
