#!/bin/bash

set -e

source "$(dirname "${BASH_SOURCE[0]}")"/scripts/common

function run_archiver {
  source secrets
  TZ=UTC python -u src/archiver.py
}

check_dependencies
start_vm
init_virtualenv
syntax_check
run_archiver
