#!/bin/bash

set -e

source "$(dirname "${BASH_SOURCE[0]}")"/scripts/common

function init_node {
  # TODO: Windows?
  if [ "$(uname -s)" = "Darwin" ]; then
    echo "Using nvm to select nodejs version"
    export NVM_DIR="$ROOT/web/.nvm"
    source "$ROOT/web/nvm.sh"
    nvm install
  else
    echo "Using system nodejs: $(node --version)"
  fi
}

function run_web {
  pushd "$ROOT/web"
  npm install
  source "$ROOT/secrets"
  npm run dev
  popd
}

start_vm
init_node
run_web
