#!/usr/bin/env bash

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/scripts/common

function run_test {
  pushd "$ROOT"
  pip install --progress-bar off -r "$ROOT/test-requirements.txt"
  source "$ROOT/secrets"
  ptw
  popd
}

check_dependencies
start_vm
init_virtualenv
syntax_check
run_test
