#!/bin/bash

set -e

source "$(dirname "${BASH_SOURCE[0]}")"/scripts/common

function run_lint {
  pip install pylint==1.8.1
  pushd "$ROOT/src"
  python -m pylint --rcfile "$ROOT/.pylintrc" *
  #python -m pylint "$ROOT/src/"*.py || true
  #python -m pylint "$ROOT/src/migration/"*.py || true
  popd
}

check_dependencies
start_vm
init_virtualenv
init_node
syntax_check
run_lint
