#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")

set -e

function cleanup {
  # Remove files generated by running tests
  find . -name "__pycache__" | xargs rm -rf
}

trap cleanup EXIT

function python_syntax_check {
  [ ! -z $(which python3) ] && local py3="$(which python3)"
  [ ! -z $(which python3.5) ] && local py3="$(which python3.5)"
  find src -name "*.py" | xargs "$py3" -m py_compile
}

ansible-playbook --syntax-check ansible/deploy.yml
python_syntax_check
tox
