version: 2

jobs:
  build:
    filters:
      branches:
        only: master
    working_directory: ~/repo
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: ./circleci.sh
