version: 2.1

workflows:
  version: 2

  deploy_on_commit:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

  deploy_daily:
    jobs:
      - deploy
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: ubuntu:16.04
      - image: postgres:9.5.13
        environment:
          POSTGRES_USER: lemon
          POSTGRES_PASSWORD: lemon
          POSTGRES_DB: lemon
      - image: redis:3.2.12

    steps:
      - checkout
      - run: ./circleci.sh
