- name: Install packages used for deployment
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - libpq-dev # FIXME: requires postgres repository?

- name: Install python packages used for deployment
  pip:
    name: "{{ item }}"
  with_items:
    - psycopg2
