- name: Create app directory for journald-cloudwatch
  file:
    path: "/opt/journald-cloudwatch"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy the journald-cloudwatch executable
  copy:
    src: "../journald-cloudwatch/target/release/journald-cloudwatch"
    dest: "/opt/journald-cloudwatch/journald-cloudwatch"
    owner: root
    group: root
    mode: 0700
  notify:
    - restart journald-cloudwatch

- name: Create systemd service
  template:
    src: "templates/journald-cloudwatch.service"
    dest: "/etc/systemd/system/journald-cloudwatch.service"
  notify:
    - reload unit files
    - restart journald-cloudwatch

- name: Enable and start service
  service:
    name: "journald-cloudwatch"
    state: started
    enabled: yes
