---
- name: Install unattended-upgrades
  apt: state=present name=unattended-upgrades

- name: Configure unattended-upgrades
  template:
    src: "{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Start unattended-upgrades
  systemd:
    name: "unattended-upgrades"
    state: restarted
    enabled: yes
